/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#61646d',
        'tertiary-fixed-dim': '#ddc39d',
        'surface-bright': '#fbf8fa',
        'on-tertiary': '#ffffff',
        'primary-container': '#1e293b',
        secondary: '#5b5e67',
        'on-error-container': '#93000a',
        'surface-container': '#f0edef',
        'on-primary-container': '#8590a6',
        'surface-tint': '#545f73',
        'secondary-container': '#dfe2ed',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-surface': '#1b1b1d',
        'surface-dim': '#dcd9db',
        'inverse-on-surface': '#f3f0f2',
        'tertiary-fixed': '#fadfb8',
        'tertiary-container': '#35260c',
        'on-background': '#1b1b1d',
        'surface-container-highest': '#e4e2e3',
        'on-primary-fixed': '#111c2d',
        'primary-fixed': '#d8e3fb',
        primary: '#091426',
        tertiary: '#1e1200',
        'on-tertiary-fixed': '#271902',
        'on-tertiary-fixed-variant': '#564427',
        outline: '#75777d',
        'surface-container-high': '#eae7e9',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#c3c6d1',
        background: '#fbf8fa',
        error: '#ba1a1a',
        'primary-fixed-dim': '#bcc7de',
        'secondary-fixed': '#dfe2ed',
        surface: '#fbf8fa',
        'inverse-surface': '#303032',
        'surface-variant': '#e4e2e3',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#181c23',
        'on-primary-fixed-variant': '#3c475a',
        'on-secondary-fixed-variant': '#43474f',
        'surface-container-low': '#f5f3f4',
        'on-surface-variant': '#45474c',
        'inverse-primary': '#bcc7de',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#a38c6a',
        'outline-variant': '#c5c6cd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '32px',
        lg: '24px',
        base: '8px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        xs: '4px',
        gutter: '16px',
        md: '16px',
        sm: '12px',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        code: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        code: ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
